metastore_direct:
  uri: "FULL_DB_URL"
  type: MYSQL | POSTGRES | ORACLE
  # Required for Oracle Connections to Select proper schema
  #initSql: "ALTER SESSION SET CURRENT_SCHEMA=<hive_schema>"
  connectionProperties:
    user: "DB_USER"
    password: "DB_PASSWORD"
  connectionPool:
    min: 3
    max: 5
parallelism: 4
queries:
  db_tbl_count:
    parameters:
      dbs:
        override: "%"
